# Generated by Django 4.1.7 on 2023-04-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('movie_id', models.IntegerField(blank=True, null=True, verbose_name='电影ID')),
                ('comment_star', models.IntegerField(blank=True, null=True, verbose_name='星级评分')),
                ('comment_content', models.TextField(blank=True, null=True, verbose_name='短评内容')),
                ('comment_time', models.DateField(blank=True, null=True, verbose_name='短评时间')),
            ],
            options={
                'db_table': 'movie_comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('detail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('directors', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('types', models.CharField(blank=True, max_length=128, null=True)),
                ('countries', models.CharField(blank=True, max_length=128, null=True)),
                ('lang', models.CharField(blank=True, max_length=128, null=True)),
                ('release_date', models.CharField(blank=True, max_length=128, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('rating_sum', models.IntegerField(blank=True, null=True)),
                ('stars_proportion', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('comment_len', models.IntegerField(blank=True, null=True)),
                ('img_list', models.TextField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'movie_detail',
                'managed': True,
            },
        ),
    ]
