# Generated by Django 4.1.7 on 2023-04-18 03:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=user.models.user_avatar_path, verbose_name='头像')),
                ('role', models.CharField(blank=True, choices=[('admin', '管理员'), ('user', '用户')], max_length=32, null=True, verbose_name='角色')),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
            options={
                'db_table': 'user_token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2023, 4, 18, 11, 39, 10, 154726))),
                ('favor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.moviedetail', verbose_name='用户收藏的电影(id)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.userinfo', verbose_name='用户(id)')),
            ],
            options={
                'db_table': 'user_favorites',
                'managed': True,
            },
        ),
    ]
