# Generated by Django 4.1.7 on 2023-04-21 08:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorites',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 16, 39, 13, 224305), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='favor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.moviedetail', verbose_name='用户收藏的电影(mid)'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.userinfo', verbose_name='用户(uid)'),
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='星级评分')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 16, 39, 13, 225302), verbose_name='创建时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.moviedetail', verbose_name='电影ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.userinfo', verbose_name='用户ID')),
            ],
            options={
                'db_table': 'user_rating',
                'managed': True,
            },
        ),
    ]
